name: downs-training
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.2=pyhff2d567_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py310h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python_abi=3.10=2_cp310
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.34.2
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - bitsandbytes==0.42.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - datasets==3.0.0
      - diffusers==0.25.0
      - dill==0.3.8
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - ftfy==6.1.1
      - huggingface-hub==0.25.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.1
      - pandas==2.2.3
      - pillow==9.4.0
      - psutil==6.0.0
      - pyarrow==17.0.0
      - python-slugify==7.0.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - scipy==1.14.1
      - sympy==1.13.3
      - text-unidecode==1.3
      - tokenizers==0.19.1
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - triton==3.0.0
      - tzdata==2024.1
      - urllib3==2.2.3
      - xxhash==3.5.0
      - yarl==1.11.1
      - zipp==3.20.2
